default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  
development:
  <<: *default
  database: managent
  username: root
  password: 
  host: 127.0.0.1

test:
  <<: *default
  database: managent_test
  username: root
  password: 
  host: 127.0.0.1
